// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.tools;

import com.android.server.jarvis.tools.AppRecordCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "AppRecord". Can be used for QueryBuilder and for referencing DB names.
 */
public final class AppRecord_ implements EntityInfo<AppRecord> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "AppRecord";

    public static final int __ENTITY_ID = 4;

    public static final Class<AppRecord> __ENTITY_CLASS = AppRecord.class;

    public static final String __DB_NAME = "AppRecord";

    public static final CursorFactory<AppRecord> __CURSOR_FACTORY = new Factory();

    @Internal
    static final AppRecordIdGetter __ID_GETTER = new AppRecordIdGetter();

    public final static AppRecord_ __INSTANCE = new AppRecord_();

    public final static io.objectbox.Property<AppRecord> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<AppRecord> packageName =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "packageName");

    public final static io.objectbox.Property<AppRecord> appLabel =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "appLabel");

    public final static io.objectbox.Property<AppRecord> sourceType =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "sourceType");

    public final static io.objectbox.Property<AppRecord> lastScanTime =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, long.class, "lastScanTime");

    public final static io.objectbox.Property<AppRecord> isActive =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, boolean.class, "isActive");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<AppRecord>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        packageName,
        appLabel,
        sourceType,
        lastScanTime,
        isActive
    };

    public final static io.objectbox.Property<AppRecord> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<AppRecord> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<AppRecord>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<AppRecord> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<AppRecord> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<AppRecord> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class AppRecordIdGetter implements IdGetter<AppRecord> {
        @Override
        public long getId(AppRecord object) {
            return object.id;
        }
    }

    /** To-many relation "tools" to target entity "ToolRecord". */
    public static final RelationInfo<AppRecord, ToolRecord> tools = new RelationInfo<>(AppRecord_.__INSTANCE, ToolRecord_.__INSTANCE,
            new ToManyGetter<AppRecord, ToolRecord>() {
                @Override
                public List<ToolRecord> getToMany(AppRecord entity) {
                    return entity.tools;
                }
            },
            ToolRecord_.appId,
            new ToOneGetter<ToolRecord, AppRecord>() {
                @Override
                public ToOne<AppRecord> getToOne(ToolRecord entity) {
                    return entity.app;
                }
            });

}
