// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.tools;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "AppRecord".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class AppRecordCursor extends Cursor<AppRecord> {
    @Internal
    static final class Factory implements CursorFactory<AppRecord> {
        @Override
        public Cursor<AppRecord> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new AppRecordCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final AppRecord_.AppRecordIdGetter ID_GETTER = AppRecord_.__ID_GETTER;


    private final static int __ID_packageName = AppRecord_.packageName.id;
    private final static int __ID_appLabel = AppRecord_.appLabel.id;
    private final static int __ID_sourceType = AppRecord_.sourceType.id;
    private final static int __ID_lastScanTime = AppRecord_.lastScanTime.id;
    private final static int __ID_isActive = AppRecord_.isActive.id;

    public AppRecordCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, AppRecord_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(AppRecord entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(AppRecord entity) {
        String packageName = entity.packageName;
        int __id1 = packageName != null ? __ID_packageName : 0;
        String appLabel = entity.appLabel;
        int __id2 = appLabel != null ? __ID_appLabel : 0;
        String sourceType = entity.sourceType;
        int __id3 = sourceType != null ? __ID_sourceType : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, packageName, __id2, appLabel,
                __id3, sourceType, 0, null,
                __ID_lastScanTime, entity.lastScanTime, __ID_isActive, entity.isActive ? 1 : 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        checkApplyToManyToDb(entity.tools, ToolRecord.class);
        return __assignedId;
    }

}
