// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.tools;

import com.android.server.jarvis.tools.ToolRecordCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "ToolRecord". Can be used for QueryBuilder and for referencing DB names.
 */
public final class ToolRecord_ implements EntityInfo<ToolRecord> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "ToolRecord";

    public static final int __ENTITY_ID = 11;

    public static final Class<ToolRecord> __ENTITY_CLASS = ToolRecord.class;

    public static final String __DB_NAME = "ToolRecord";

    public static final CursorFactory<ToolRecord> __CURSOR_FACTORY = new Factory();

    @Internal
    static final ToolRecordIdGetter __ID_GETTER = new ToolRecordIdGetter();

    public final static ToolRecord_ __INSTANCE = new ToolRecord_();

    public final static io.objectbox.Property<ToolRecord> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<ToolRecord> toolName =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "toolName");

    public final static io.objectbox.Property<ToolRecord> description =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "description");

    public final static io.objectbox.Property<ToolRecord> paramsJson =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "paramsJson");

    public final static io.objectbox.Property<ToolRecord> rawDefinition =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "rawDefinition");

    public final static io.objectbox.Property<ToolRecord> receiverClass =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "receiverClass");

    public final static io.objectbox.Property<ToolRecord> cactusIndexId =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, int.class, "cactusIndexId");

    public final static io.objectbox.Property<ToolRecord> requiresConfirmation =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, boolean.class, "requiresConfirmation");

    public final static io.objectbox.Property<ToolRecord> appId =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, long.class, "appId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<ToolRecord>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        toolName,
        description,
        paramsJson,
        rawDefinition,
        receiverClass,
        cactusIndexId,
        requiresConfirmation,
        appId
    };

    public final static io.objectbox.Property<ToolRecord> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<ToolRecord> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<ToolRecord>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<ToolRecord> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<ToolRecord> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<ToolRecord> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class ToolRecordIdGetter implements IdGetter<ToolRecord> {
        @Override
        public long getId(ToolRecord object) {
            return object.id;
        }
    }

    /** To-one relation "app" to target entity "AppRecord". */
    public static final RelationInfo<ToolRecord, AppRecord> app =
            new RelationInfo<>(ToolRecord_.__INSTANCE, AppRecord_.__INSTANCE, appId, new ToOneGetter<ToolRecord, AppRecord>() {
                @Override
                public ToOne<AppRecord> getToOne(ToolRecord entity) {
                    return entity.app;
                }
            });

}
