// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.tools;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "ToolRecord".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class ToolRecordCursor extends Cursor<ToolRecord> {
    @Internal
    static final class Factory implements CursorFactory<ToolRecord> {
        @Override
        public Cursor<ToolRecord> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new ToolRecordCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final ToolRecord_.ToolRecordIdGetter ID_GETTER = ToolRecord_.__ID_GETTER;


    private final static int __ID_toolName = ToolRecord_.toolName.id;
    private final static int __ID_description = ToolRecord_.description.id;
    private final static int __ID_paramsJson = ToolRecord_.paramsJson.id;
    private final static int __ID_rawDefinition = ToolRecord_.rawDefinition.id;
    private final static int __ID_receiverClass = ToolRecord_.receiverClass.id;
    private final static int __ID_cactusIndexId = ToolRecord_.cactusIndexId.id;
    private final static int __ID_requiresConfirmation = ToolRecord_.requiresConfirmation.id;
    private final static int __ID_appId = ToolRecord_.appId.id;

    public ToolRecordCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, ToolRecord_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(ToolRecord entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(ToolRecord entity) {
        ToOne<AppRecord> app = entity.app;
        if(app != null && app.internalRequiresPutTarget()) {
            Cursor<AppRecord> targetCursor = getRelationTargetCursor(AppRecord.class);
            try {
                app.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String toolName = entity.toolName;
        int __id1 = toolName != null ? __ID_toolName : 0;
        String description = entity.description;
        int __id2 = description != null ? __ID_description : 0;
        String paramsJson = entity.paramsJson;
        int __id3 = paramsJson != null ? __ID_paramsJson : 0;
        String rawDefinition = entity.rawDefinition;
        int __id4 = rawDefinition != null ? __ID_rawDefinition : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, toolName, __id2, description,
                __id3, paramsJson, __id4, rawDefinition);

        String receiverClass = entity.receiverClass;
        int __id5 = receiverClass != null ? __ID_receiverClass : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                __id5, receiverClass, 0, null,
                0, null, 0, null,
                __ID_appId, entity.app.getTargetId(), __ID_cactusIndexId, entity.cactusIndexId,
                __ID_requiresConfirmation, entity.requiresConfirmation ? 1 : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        return __assignedId;
    }

}
