package com.android.server.jarvis.model;

import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.model.PropertyType;
import io.objectbox.Property;

/**
 * Hand-written ObjectBox EntityInfo stub for AgentSession.
 *
 * Generated by objectbox-processor when wired up. Until then this stub
 * allows compilation and QueryBuilder usage. getCursorFactory() throws —
 * actual box reads/writes depend on full processor-generated cursor.
 */
@Internal
public final class AgentSession_ implements EntityInfo<AgentSession> {

    public static final AgentSession_ INSTANCE = new AgentSession_();

    // Properties
    public static final Property<AgentSession> id;
    public static final Property<AgentSession> sessionId;
    public static final Property<AgentSession> originalQuery;
    public static final Property<AgentSession> currentPlan;
    public static final Property<AgentSession> lastToolResult;
    public static final Property<AgentSession> accumulatedContext;
    public static final Property<AgentSession> turnCount;
    public static final Property<AgentSession> maxTurns;
    public static final Property<AgentSession> status;
    public static final Property<AgentSession> finalAnswer;
    public static final Property<AgentSession> createdAt;
    public static final Property<AgentSession> lastUpdatedAt;

    static {
        id                 = new Property<>(INSTANCE, 0,  PropertyType.Long,   long.class,   "id",                 true,  "id");
        sessionId          = new Property<>(INSTANCE, 1,  PropertyType.String, String.class, "sessionId",          false, "sessionId");
        originalQuery      = new Property<>(INSTANCE, 2,  PropertyType.String, String.class, "originalQuery",      false, "originalQuery");
        currentPlan        = new Property<>(INSTANCE, 3,  PropertyType.String, String.class, "currentPlan",        false, "currentPlan");
        lastToolResult     = new Property<>(INSTANCE, 4,  PropertyType.String, String.class, "lastToolResult",     false, "lastToolResult");
        accumulatedContext = new Property<>(INSTANCE, 5,  PropertyType.String, String.class, "accumulatedContext", false, "accumulatedContext");
        turnCount          = new Property<>(INSTANCE, 6,  PropertyType.Int,    int.class,    "turnCount",          false, "turnCount");
        maxTurns           = new Property<>(INSTANCE, 7,  PropertyType.Int,    int.class,    "maxTurns",           false, "maxTurns");
        status             = new Property<>(INSTANCE, 8,  PropertyType.String, String.class, "status",             false, "status");
        finalAnswer        = new Property<>(INSTANCE, 9,  PropertyType.String, String.class, "finalAnswer",        false, "finalAnswer");
        createdAt          = new Property<>(INSTANCE, 10, PropertyType.Long,   long.class,   "createdAt",          false, "createdAt");
        lastUpdatedAt      = new Property<>(INSTANCE, 11, PropertyType.Long,   long.class,   "lastUpdatedAt",      false, "lastUpdatedAt");
    }

    @Override public String getEntityName()  { return "AgentSession"; }
    @Override public String getDbName()      { return "AgentSession"; }
    @Override public Class<AgentSession> getEntityClass() { return AgentSession.class; }
    @Override public int getEntityId()       { return 7; }

    @Override
    public Property<AgentSession>[] getAllProperties() {
        return new Property[]{ id, sessionId, originalQuery, currentPlan, lastToolResult,
                accumulatedContext, turnCount, maxTurns, status, finalAnswer,
                createdAt, lastUpdatedAt };
    }

    @Override public Property<AgentSession> getIdProperty() { return id; }

    @Override
    public IdGetter<AgentSession> getIdGetter() {
        return entity -> entity.id;
    }

    @Override
    public CursorFactory<AgentSession> getCursorFactory() {
        throw new UnsupportedOperationException(
                "AgentSession_ is a hand-written stub. "
                + "Wire objectbox-processor to generate a real cursor.");
    }
}
