#!/bin/bash
# Regenerates the ObjectBox code for the JarvisOS entities.
#
# The ObjectBox annotation processor is Kotlin-based and pulls in a dozen Maven
# artifacts, so it is not wired into Soong. Instead it is run here, on the
# host, and its output (the *_ and *Cursor classes plus MyObjectBox) is checked
# in next to the entities. Re-run this after adding, removing or changing an
# @Entity class, and commit the result together with objectbox/default.json:
# that file holds the schema UIDs and must stay stable across builds, or an
# existing on-device store will not open.
#
# ObjectBox's Gradle plugin also rewrites entity bytecode to initialise
# relation fields. Nothing does that here, so every entity with a ToOne/ToMany
# must declare `transient BoxStore __boxStore;` and initialise the relation
# fields itself (see AgentSession for the pattern).
set -euo pipefail

OBX_VERSION=4.0.3
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE/../java"
TOP="$(cd "$HERE/../../../../.." && pwd)"
JAVAC="${JAVAC:-$TOP/prebuilts/jdk/jdk21/linux-x86/bin/javac}"
CACHE="${OBX_CACHE:-$HOME/.cache/jarvis-objectbox/$OBX_VERSION}"
MAVEN=https://repo1.maven.org/maven2

# io.objectbox:objectbox-processor and its runtime closure.
ARTIFACTS=(
    io/objectbox/objectbox-processor/$OBX_VERSION
    io/objectbox/objectbox-generator/$OBX_VERSION
    io/objectbox/objectbox-code-modifier/$OBX_VERSION
    io/objectbox/objectbox-java/$OBX_VERSION
    io/objectbox/objectbox-java-api/$OBX_VERSION
    org/greenrobot/essentials/3.1.0
    org/freemarker/freemarker/2.3.32
    org/javassist/javassist/3.29.2-GA
    com/squareup/moshi/moshi/1.15.0
    com/squareup/okio/okio/2.10.0
    com/google/code/findbugs/jsr305/3.0.2
    net/ltgt/gradle/incap/incap/1.0.0
    org/jetbrains/kotlin/kotlin-stdlib/1.8.20
    org/jetbrains/kotlin/kotlin-stdlib-common/1.8.20
    org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.20
    org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.20
    org/jetbrains/annotations/13.0
    # Only reached by the processor's build-statistics reporter, which fails
    # the whole run if these are missing. See the unshare below.
    com/google/crypto/tink/tink/1.12.0
    com/google/code/gson/gson/2.10.1
    com/google/protobuf/protobuf-java/3.24.3
    com/google/errorprone/error_prone_annotations/2.22.0
)

mkdir -p "$CACHE"
CP=
for a in "${ARTIFACTS[@]}"; do
    version="${a##*/}"; name="${a%/*}"; name="${name##*/}"
    jar="$CACHE/$name-$version.jar"
    [ -s "$jar" ] || curl -fsSL -o "$jar" "$MAVEN/$a/$name-$version.jar"
    CP="$CP:$jar"
done
CP="${CP#:}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/in" "$WORK/gen" "$WORK/cls"

# Only the entities go in: the rest of the service needs the Android framework.
(cd "$SRC" && grep -rl '^@Entity' --include='*.java' .) | while read -r f; do
    mkdir -p "$WORK/in/$(dirname "$f")"
    cp "$SRC/$f" "$WORK/in/$f"
done

# The processor reports build statistics to ObjectBox on every run. Run it in
# an empty network namespace so nothing leaves the machine.
unshare -n true 2>/dev/null || { echo "need 'unshare -n' (run as root) to keep the processor offline" >&2; exit 1; }
unshare -n "$JAVAC" -proc:only -nowarn \
    -processorpath "$CP" -cp "$CP" \
    -processor io.objectbox.processor.ObjectBoxProcessorShim \
    -Aobjectbox.modelPath="$HERE/default.json" \
    -Aobjectbox.myObjectBoxPackage=com.android.server.jarvis.core \
    -s "$WORK/gen" -d "$WORK/cls" \
    $(find "$WORK/in" -name '*.java')

# Drop previously generated files so a deleted entity does not leave orphans.
{ grep -rl '^// Generated by objectbox/regenerate.sh' --include='*.java' "$SRC" || true; } | xargs -r rm -f

(cd "$WORK/gen" && find . -name '*.java') | while read -r f; do
    { echo '// Generated by objectbox/regenerate.sh — do not edit.'; cat "$WORK/gen/$f"; } > "$SRC/$f"
done
echo "Generated $(find "$WORK/gen" -name '*.java' | wc -l) files; model: $HERE/default.json"
