#!/bin/bash
# Compiles the entities and the generated ObjectBox code on the host and runs
# StoreSmokeTest against the Linux build of the ObjectBox native library.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE/../java"
TOP="$(cd "$HERE/../../../../.." && pwd)"
JDK="${JAVA_HOME:-$TOP/prebuilts/jdk/jdk21/linux-x86}"
OBX="$TOP/vendor/jarvisos/prebuilts/objectbox"
CP="$OBX/lib/java/objectbox-java-4.0.3.jar:$OBX/lib/java/objectbox-java-api-4.0.3.jar"
CP="$CP:$OBX/lib/java/essentials-3.1.0.jar:$OBX/objectbox-linux-4.0.3.jar"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
SOURCES=$(cd "$SRC" && { grep -rl '^@Entity' --include='*.java' .; \
    grep -rl '^// Generated by objectbox/regenerate.sh' --include='*.java' .; } | sed "s#^#$SRC/#")
"$JDK/bin/javac" -nowarn -cp "$CP" -d "$WORK" $SOURCES "$HERE/StoreSmokeTest.java"
# ObjectBox unpacks its native library into the working directory.
cd "$WORK"
"$JDK/bin/java" -cp "$WORK:$CP" StoreSmokeTest
