// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.AccessLogCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "AccessLog". Can be used for QueryBuilder and for referencing DB names.
 */
public final class AccessLog_ implements EntityInfo<AccessLog> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "AccessLog";

    public static final int __ENTITY_ID = 1;

    public static final Class<AccessLog> __ENTITY_CLASS = AccessLog.class;

    public static final String __DB_NAME = "AccessLog";

    public static final CursorFactory<AccessLog> __CURSOR_FACTORY = new Factory();

    @Internal
    static final AccessLogIdGetter __ID_GETTER = new AccessLogIdGetter();

    public final static AccessLog_ __INSTANCE = new AccessLog_();

    public final static io.objectbox.Property<AccessLog> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<AccessLog> fileId =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, long.class, "fileId");

    public final static io.objectbox.Property<AccessLog> conversationId =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, long.class, "conversationId");

    public final static io.objectbox.Property<AccessLog> accessedAt =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "accessedAt");

    public final static io.objectbox.Property<AccessLog> wasHelpful =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, boolean.class, "wasHelpful");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<AccessLog>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        fileId,
        conversationId,
        accessedAt,
        wasHelpful
    };

    public final static io.objectbox.Property<AccessLog> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<AccessLog> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<AccessLog>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<AccessLog> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<AccessLog> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<AccessLog> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class AccessLogIdGetter implements IdGetter<AccessLog> {
        @Override
        public long getId(AccessLog object) {
            return object.id;
        }
    }

}
