// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "AccessLog".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class AccessLogCursor extends Cursor<AccessLog> {
    @Internal
    static final class Factory implements CursorFactory<AccessLog> {
        @Override
        public Cursor<AccessLog> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new AccessLogCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final AccessLog_.AccessLogIdGetter ID_GETTER = AccessLog_.__ID_GETTER;


    private final static int __ID_fileId = AccessLog_.fileId.id;
    private final static int __ID_conversationId = AccessLog_.conversationId.id;
    private final static int __ID_accessedAt = AccessLog_.accessedAt.id;
    private final static int __ID_wasHelpful = AccessLog_.wasHelpful.id;

    public AccessLogCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, AccessLog_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(AccessLog entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(AccessLog entity) {
        long __assignedId = collect004000(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __ID_fileId, entity.fileId, __ID_conversationId, entity.conversationId,
                __ID_accessedAt, entity.accessedAt, __ID_wasHelpful, entity.wasHelpful ? 1 : 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
