// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.AgentTurnCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "AgentTurn". Can be used for QueryBuilder and for referencing DB names.
 */
public final class AgentTurn_ implements EntityInfo<AgentTurn> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "AgentTurn";

    public static final int __ENTITY_ID = 3;

    public static final Class<AgentTurn> __ENTITY_CLASS = AgentTurn.class;

    public static final String __DB_NAME = "AgentTurn";

    public static final CursorFactory<AgentTurn> __CURSOR_FACTORY = new Factory();

    @Internal
    static final AgentTurnIdGetter __ID_GETTER = new AgentTurnIdGetter();

    public final static AgentTurn_ __INSTANCE = new AgentTurn_();

    public final static io.objectbox.Property<AgentTurn> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<AgentTurn> role =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "role");

    public final static io.objectbox.Property<AgentTurn> content =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "content");

    public final static io.objectbox.Property<AgentTurn> toolName =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "toolName");

    public final static io.objectbox.Property<AgentTurn> toolArgs =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "toolArgs");

    public final static io.objectbox.Property<AgentTurn> timestamp =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "timestamp");

    public final static io.objectbox.Property<AgentTurn> sessionId =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, long.class, "sessionId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<AgentTurn>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        role,
        content,
        toolName,
        toolArgs,
        timestamp,
        sessionId
    };

    public final static io.objectbox.Property<AgentTurn> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<AgentTurn> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<AgentTurn>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<AgentTurn> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<AgentTurn> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<AgentTurn> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class AgentTurnIdGetter implements IdGetter<AgentTurn> {
        @Override
        public long getId(AgentTurn object) {
            return object.id;
        }
    }

    /** To-one relation "session" to target entity "AgentSession". */
    public static final RelationInfo<AgentTurn, AgentSession> session =
            new RelationInfo<>(AgentTurn_.__INSTANCE, AgentSession_.__INSTANCE, sessionId, new ToOneGetter<AgentTurn, AgentSession>() {
                @Override
                public ToOne<AgentSession> getToOne(AgentTurn entity) {
                    return entity.session;
                }
            });

}
