// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.AgentSessionCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "AgentSession". Can be used for QueryBuilder and for referencing DB names.
 */
public final class AgentSession_ implements EntityInfo<AgentSession> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "AgentSession";

    public static final int __ENTITY_ID = 2;

    public static final Class<AgentSession> __ENTITY_CLASS = AgentSession.class;

    public static final String __DB_NAME = "AgentSession";

    public static final CursorFactory<AgentSession> __CURSOR_FACTORY = new Factory();

    @Internal
    static final AgentSessionIdGetter __ID_GETTER = new AgentSessionIdGetter();

    public final static AgentSession_ __INSTANCE = new AgentSession_();

    public final static io.objectbox.Property<AgentSession> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<AgentSession> sessionId =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "sessionId");

    public final static io.objectbox.Property<AgentSession> originalQuery =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "originalQuery");

    public final static io.objectbox.Property<AgentSession> currentPlan =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "currentPlan");

    public final static io.objectbox.Property<AgentSession> lastToolResult =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "lastToolResult");

    public final static io.objectbox.Property<AgentSession> accumulatedContext =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "accumulatedContext");

    public final static io.objectbox.Property<AgentSession> turnCount =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, int.class, "turnCount");

    public final static io.objectbox.Property<AgentSession> maxTurns =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, int.class, "maxTurns");

    public final static io.objectbox.Property<AgentSession> status =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, String.class, "status");

    public final static io.objectbox.Property<AgentSession> finalAnswer =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, String.class, "finalAnswer");

    public final static io.objectbox.Property<AgentSession> createdAt =
        new io.objectbox.Property<>(__INSTANCE, 10, 11, long.class, "createdAt");

    public final static io.objectbox.Property<AgentSession> lastUpdatedAt =
        new io.objectbox.Property<>(__INSTANCE, 11, 12, long.class, "lastUpdatedAt");

    public final static io.objectbox.Property<AgentSession> consolidated =
        new io.objectbox.Property<>(__INSTANCE, 12, 13, boolean.class, "consolidated");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<AgentSession>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        sessionId,
        originalQuery,
        currentPlan,
        lastToolResult,
        accumulatedContext,
        turnCount,
        maxTurns,
        status,
        finalAnswer,
        createdAt,
        lastUpdatedAt,
        consolidated
    };

    public final static io.objectbox.Property<AgentSession> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<AgentSession> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<AgentSession>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<AgentSession> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<AgentSession> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<AgentSession> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class AgentSessionIdGetter implements IdGetter<AgentSession> {
        @Override
        public long getId(AgentSession object) {
            return object.id;
        }
    }

    /** To-many relation "turns" to target entity "AgentTurn". */
    public static final RelationInfo<AgentSession, AgentTurn> turns = new RelationInfo<>(AgentSession_.__INSTANCE, AgentTurn_.__INSTANCE,
            new ToManyGetter<AgentSession, AgentTurn>() {
                @Override
                public List<AgentTurn> getToMany(AgentSession entity) {
                    return entity.turns;
                }
            },
            AgentTurn_.sessionId,
            new ToOneGetter<AgentTurn, AgentSession>() {
                @Override
                public ToOne<AgentSession> getToOne(AgentTurn entity) {
                    return entity.session;
                }
            });

}
