// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "AgentTurn".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class AgentTurnCursor extends Cursor<AgentTurn> {
    @Internal
    static final class Factory implements CursorFactory<AgentTurn> {
        @Override
        public Cursor<AgentTurn> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new AgentTurnCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final AgentTurn_.AgentTurnIdGetter ID_GETTER = AgentTurn_.__ID_GETTER;


    private final static int __ID_role = AgentTurn_.role.id;
    private final static int __ID_content = AgentTurn_.content.id;
    private final static int __ID_toolName = AgentTurn_.toolName.id;
    private final static int __ID_toolArgs = AgentTurn_.toolArgs.id;
    private final static int __ID_timestamp = AgentTurn_.timestamp.id;
    private final static int __ID_sessionId = AgentTurn_.sessionId.id;

    public AgentTurnCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, AgentTurn_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(AgentTurn entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(AgentTurn entity) {
        ToOne<AgentSession> session = entity.session;
        if(session != null && session.internalRequiresPutTarget()) {
            Cursor<AgentSession> targetCursor = getRelationTargetCursor(AgentSession.class);
            try {
                session.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String role = entity.role;
        int __id1 = role != null ? __ID_role : 0;
        String content = entity.content;
        int __id2 = content != null ? __ID_content : 0;
        String toolName = entity.toolName;
        int __id3 = toolName != null ? __ID_toolName : 0;
        String toolArgs = entity.toolArgs;
        int __id4 = toolArgs != null ? __ID_toolArgs : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, role, __id2, content,
                __id3, toolName, __id4, toolArgs);

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __ID_timestamp, entity.timestamp, __ID_sessionId, entity.session.getTargetId(),
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        return __assignedId;
    }

}
