// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "AgentSession".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class AgentSessionCursor extends Cursor<AgentSession> {
    @Internal
    static final class Factory implements CursorFactory<AgentSession> {
        @Override
        public Cursor<AgentSession> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new AgentSessionCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final AgentSession_.AgentSessionIdGetter ID_GETTER = AgentSession_.__ID_GETTER;


    private final static int __ID_sessionId = AgentSession_.sessionId.id;
    private final static int __ID_originalQuery = AgentSession_.originalQuery.id;
    private final static int __ID_currentPlan = AgentSession_.currentPlan.id;
    private final static int __ID_lastToolResult = AgentSession_.lastToolResult.id;
    private final static int __ID_accumulatedContext = AgentSession_.accumulatedContext.id;
    private final static int __ID_turnCount = AgentSession_.turnCount.id;
    private final static int __ID_maxTurns = AgentSession_.maxTurns.id;
    private final static int __ID_status = AgentSession_.status.id;
    private final static int __ID_finalAnswer = AgentSession_.finalAnswer.id;
    private final static int __ID_createdAt = AgentSession_.createdAt.id;
    private final static int __ID_lastUpdatedAt = AgentSession_.lastUpdatedAt.id;
    private final static int __ID_consolidated = AgentSession_.consolidated.id;

    public AgentSessionCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, AgentSession_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(AgentSession entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(AgentSession entity) {
        String sessionId = entity.sessionId;
        int __id1 = sessionId != null ? __ID_sessionId : 0;
        String originalQuery = entity.originalQuery;
        int __id2 = originalQuery != null ? __ID_originalQuery : 0;
        String currentPlan = entity.currentPlan;
        int __id3 = currentPlan != null ? __ID_currentPlan : 0;
        String lastToolResult = entity.lastToolResult;
        int __id4 = lastToolResult != null ? __ID_lastToolResult : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, sessionId, __id2, originalQuery,
                __id3, currentPlan, __id4, lastToolResult);

        String accumulatedContext = entity.accumulatedContext;
        int __id5 = accumulatedContext != null ? __ID_accumulatedContext : 0;
        String status = entity.status;
        int __id8 = status != null ? __ID_status : 0;
        String finalAnswer = entity.finalAnswer;
        int __id9 = finalAnswer != null ? __ID_finalAnswer : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                __id5, accumulatedContext, __id8, status,
                __id9, finalAnswer, 0, null,
                __ID_createdAt, entity.createdAt, __ID_lastUpdatedAt, entity.lastUpdatedAt,
                __ID_turnCount, entity.turnCount, __ID_maxTurns, entity.maxTurns,
                __ID_consolidated, entity.consolidated ? 1 : 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        checkApplyToManyToDb(entity.turns, AgentTurn.class);
        return __assignedId;
    }

}
