// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.ConversationCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Conversation". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Conversation_ implements EntityInfo<Conversation> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Conversation";

    public static final int __ENTITY_ID = 5;

    public static final Class<Conversation> __ENTITY_CLASS = Conversation.class;

    public static final String __DB_NAME = "Conversation";

    public static final CursorFactory<Conversation> __CURSOR_FACTORY = new Factory();

    @Internal
    static final ConversationIdGetter __ID_GETTER = new ConversationIdGetter();

    public final static Conversation_ __INSTANCE = new Conversation_();

    public final static io.objectbox.Property<Conversation> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Conversation> title =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "title");

    public final static io.objectbox.Property<Conversation> createdAt =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, long.class, "createdAt");

    public final static io.objectbox.Property<Conversation> lastMessageAt =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "lastMessageAt");

    public final static io.objectbox.Property<Conversation> lastMessagePreview =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "lastMessagePreview");

    public final static io.objectbox.Property<Conversation> mode =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "mode");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Conversation>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        title,
        createdAt,
        lastMessageAt,
        lastMessagePreview,
        mode
    };

    public final static io.objectbox.Property<Conversation> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Conversation> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Conversation>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Conversation> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Conversation> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Conversation> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class ConversationIdGetter implements IdGetter<Conversation> {
        @Override
        public long getId(Conversation object) {
            return object.id;
        }
    }

    /** To-many relation "referencedFiles" to target entity "SourceFile". */
    public static final RelationInfo<Conversation, SourceFile> referencedFiles = new RelationInfo<>(Conversation_.__INSTANCE, SourceFile_.__INSTANCE,
            new ToManyGetter<Conversation, SourceFile>() {
                @Override
                public List<SourceFile> getToMany(Conversation entity) {
                    return entity.referencedFiles;
                }
            },
             1);

    /** To-many relation "messages" to target entity "Message". */
    public static final RelationInfo<Conversation, Message> messages = new RelationInfo<>(Conversation_.__INSTANCE, Message_.__INSTANCE,
            new ToManyGetter<Conversation, Message>() {
                @Override
                public List<Message> getToMany(Conversation entity) {
                    return entity.messages;
                }
            },
            Message_.conversationId,
            new ToOneGetter<Message, Conversation>() {
                @Override
                public ToOne<Conversation> getToOne(Message entity) {
                    return entity.conversation;
                }
            });

}
