// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Conversation".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class ConversationCursor extends Cursor<Conversation> {
    @Internal
    static final class Factory implements CursorFactory<Conversation> {
        @Override
        public Cursor<Conversation> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new ConversationCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Conversation_.ConversationIdGetter ID_GETTER = Conversation_.__ID_GETTER;


    private final static int __ID_title = Conversation_.title.id;
    private final static int __ID_createdAt = Conversation_.createdAt.id;
    private final static int __ID_lastMessageAt = Conversation_.lastMessageAt.id;
    private final static int __ID_lastMessagePreview = Conversation_.lastMessagePreview.id;
    private final static int __ID_mode = Conversation_.mode.id;

    public ConversationCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Conversation_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Conversation entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Conversation entity) {
        String title = entity.title;
        int __id1 = title != null ? __ID_title : 0;
        String lastMessagePreview = entity.lastMessagePreview;
        int __id4 = lastMessagePreview != null ? __ID_lastMessagePreview : 0;
        String mode = entity.mode;
        int __id5 = mode != null ? __ID_mode : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, title, __id4, lastMessagePreview,
                __id5, mode, 0, null,
                __ID_createdAt, entity.createdAt, __ID_lastMessageAt, entity.lastMessageAt,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        checkApplyToManyToDb(entity.referencedFiles, SourceFile.class);
        checkApplyToManyToDb(entity.messages, Message.class);
        return __assignedId;
    }

}
