// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.DocumentChunkCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "DocumentChunk". Can be used for QueryBuilder and for referencing DB names.
 */
public final class DocumentChunk_ implements EntityInfo<DocumentChunk> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "DocumentChunk";

    public static final int __ENTITY_ID = 6;

    public static final Class<DocumentChunk> __ENTITY_CLASS = DocumentChunk.class;

    public static final String __DB_NAME = "DocumentChunk";

    public static final CursorFactory<DocumentChunk> __CURSOR_FACTORY = new Factory();

    @Internal
    static final DocumentChunkIdGetter __ID_GETTER = new DocumentChunkIdGetter();

    public final static DocumentChunk_ __INSTANCE = new DocumentChunk_();

    public final static io.objectbox.Property<DocumentChunk> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<DocumentChunk> cactusIndexId =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, int.class, "cactusIndexId");

    public final static io.objectbox.Property<DocumentChunk> chunkIndex =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, int.class, "chunkIndex");

    public final static io.objectbox.Property<DocumentChunk> summary =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "summary");

    public final static io.objectbox.Property<DocumentChunk> tokenCount =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, int.class, "tokenCount");

    public final static io.objectbox.Property<DocumentChunk> embeddedAt =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "embeddedAt");

    public final static io.objectbox.Property<DocumentChunk> embeddingRetained =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, boolean.class, "embeddingRetained");

    public final static io.objectbox.Property<DocumentChunk> sourceFileId =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, long.class, "sourceFileId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<DocumentChunk>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        cactusIndexId,
        chunkIndex,
        summary,
        tokenCount,
        embeddedAt,
        embeddingRetained,
        sourceFileId
    };

    public final static io.objectbox.Property<DocumentChunk> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<DocumentChunk> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<DocumentChunk>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<DocumentChunk> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<DocumentChunk> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<DocumentChunk> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class DocumentChunkIdGetter implements IdGetter<DocumentChunk> {
        @Override
        public long getId(DocumentChunk object) {
            return object.id;
        }
    }

    /** To-one relation "sourceFile" to target entity "SourceFile". */
    public static final RelationInfo<DocumentChunk, SourceFile> sourceFile =
            new RelationInfo<>(DocumentChunk_.__INSTANCE, SourceFile_.__INSTANCE, sourceFileId, new ToOneGetter<DocumentChunk, SourceFile>() {
                @Override
                public ToOne<SourceFile> getToOne(DocumentChunk entity) {
                    return entity.sourceFile;
                }
            });

}
