// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "DocumentChunk".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class DocumentChunkCursor extends Cursor<DocumentChunk> {
    @Internal
    static final class Factory implements CursorFactory<DocumentChunk> {
        @Override
        public Cursor<DocumentChunk> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new DocumentChunkCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final DocumentChunk_.DocumentChunkIdGetter ID_GETTER = DocumentChunk_.__ID_GETTER;


    private final static int __ID_cactusIndexId = DocumentChunk_.cactusIndexId.id;
    private final static int __ID_chunkIndex = DocumentChunk_.chunkIndex.id;
    private final static int __ID_summary = DocumentChunk_.summary.id;
    private final static int __ID_tokenCount = DocumentChunk_.tokenCount.id;
    private final static int __ID_embeddedAt = DocumentChunk_.embeddedAt.id;
    private final static int __ID_embeddingRetained = DocumentChunk_.embeddingRetained.id;
    private final static int __ID_sourceFileId = DocumentChunk_.sourceFileId.id;

    public DocumentChunkCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, DocumentChunk_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(DocumentChunk entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(DocumentChunk entity) {
        ToOne<SourceFile> sourceFile = entity.sourceFile;
        if(sourceFile != null && sourceFile.internalRequiresPutTarget()) {
            Cursor<SourceFile> targetCursor = getRelationTargetCursor(SourceFile.class);
            try {
                sourceFile.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String summary = entity.summary;
        int __id3 = summary != null ? __ID_summary : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id3, summary, 0, null,
                0, null, 0, null,
                __ID_embeddedAt, entity.embeddedAt, __ID_sourceFileId, entity.sourceFile.getTargetId(),
                __ID_cactusIndexId, entity.cactusIndexId, __ID_chunkIndex, entity.chunkIndex,
                __ID_tokenCount, entity.tokenCount, __ID_embeddingRetained, entity.embeddingRetained ? 1 : 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        return __assignedId;
    }

}
