// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Folder".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class FolderCursor extends Cursor<Folder> {
    @Internal
    static final class Factory implements CursorFactory<Folder> {
        @Override
        public Cursor<Folder> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new FolderCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Folder_.FolderIdGetter ID_GETTER = Folder_.__ID_GETTER;


    private final static int __ID_folderPath = Folder_.folderPath.id;
    private final static int __ID_displayName = Folder_.displayName.id;
    private final static int __ID_tags = Folder_.tags.id;
    private final static int __ID_summary = Folder_.summary.id;
    private final static int __ID_fileCount = Folder_.fileCount.id;
    private final static int __ID_lastUpdatedAt = Folder_.lastUpdatedAt.id;
    private final static int __ID_parentFolderId = Folder_.parentFolderId.id;

    public FolderCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Folder_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Folder entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Folder entity) {
        ToOne<Folder> parentFolder = entity.parentFolder;
        if(parentFolder != null && parentFolder.internalRequiresPutTarget()) {
            Cursor<Folder> targetCursor = getRelationTargetCursor(Folder.class);
            try {
                parentFolder.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String folderPath = entity.folderPath;
        int __id1 = folderPath != null ? __ID_folderPath : 0;
        String displayName = entity.displayName;
        int __id2 = displayName != null ? __ID_displayName : 0;
        String tags = entity.tags;
        int __id3 = tags != null ? __ID_tags : 0;
        String summary = entity.summary;
        int __id4 = summary != null ? __ID_summary : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, folderPath, __id2, displayName,
                __id3, tags, __id4, summary);

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __ID_lastUpdatedAt, entity.lastUpdatedAt, __ID_parentFolderId, entity.parentFolder.getTargetId(),
                __ID_fileCount, entity.fileCount, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        checkApplyToManyToDb(entity.files, SourceFile.class);
        checkApplyToManyToDb(entity.subFolders, Folder.class);
        return __assignedId;
    }

}
