// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.FolderCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Folder". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Folder_ implements EntityInfo<Folder> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Folder";

    public static final int __ENTITY_ID = 7;

    public static final Class<Folder> __ENTITY_CLASS = Folder.class;

    public static final String __DB_NAME = "Folder";

    public static final CursorFactory<Folder> __CURSOR_FACTORY = new Factory();

    @Internal
    static final FolderIdGetter __ID_GETTER = new FolderIdGetter();

    public final static Folder_ __INSTANCE = new Folder_();

    public final static io.objectbox.Property<Folder> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Folder> folderPath =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "folderPath");

    public final static io.objectbox.Property<Folder> displayName =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "displayName");

    public final static io.objectbox.Property<Folder> tags =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "tags");

    public final static io.objectbox.Property<Folder> summary =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "summary");

    public final static io.objectbox.Property<Folder> fileCount =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, int.class, "fileCount");

    public final static io.objectbox.Property<Folder> lastUpdatedAt =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, long.class, "lastUpdatedAt");

    public final static io.objectbox.Property<Folder> parentFolderId =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, long.class, "parentFolderId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Folder>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        folderPath,
        displayName,
        tags,
        summary,
        fileCount,
        lastUpdatedAt,
        parentFolderId
    };

    public final static io.objectbox.Property<Folder> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Folder> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Folder>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Folder> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Folder> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Folder> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class FolderIdGetter implements IdGetter<Folder> {
        @Override
        public long getId(Folder object) {
            return object.id;
        }
    }

    /** To-one relation "parentFolder" to target entity "Folder". */
    public static final RelationInfo<Folder, Folder> parentFolder =
            new RelationInfo<>(Folder_.__INSTANCE, Folder_.__INSTANCE, parentFolderId, new ToOneGetter<Folder, Folder>() {
                @Override
                public ToOne<Folder> getToOne(Folder entity) {
                    return entity.parentFolder;
                }
            });

    /** To-many relation "files" to target entity "SourceFile". */
    public static final RelationInfo<Folder, SourceFile> files = new RelationInfo<>(Folder_.__INSTANCE, SourceFile_.__INSTANCE,
            new ToManyGetter<Folder, SourceFile>() {
                @Override
                public List<SourceFile> getToMany(Folder entity) {
                    return entity.files;
                }
            },
            SourceFile_.folderId,
            new ToOneGetter<SourceFile, Folder>() {
                @Override
                public ToOne<Folder> getToOne(SourceFile entity) {
                    return entity.folder;
                }
            });

    /** To-many relation "subFolders" to target entity "Folder". */
    public static final RelationInfo<Folder, Folder> subFolders = new RelationInfo<>(Folder_.__INSTANCE, Folder_.__INSTANCE,
            new ToManyGetter<Folder, Folder>() {
                @Override
                public List<Folder> getToMany(Folder entity) {
                    return entity.subFolders;
                }
            },
            Folder_.parentFolderId,
            new ToOneGetter<Folder, Folder>() {
                @Override
                public ToOne<Folder> getToOne(Folder entity) {
                    return entity.parentFolder;
                }
            });

}
