// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.MessageCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "Message". Can be used for QueryBuilder and for referencing DB names.
 */
public final class Message_ implements EntityInfo<Message> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "Message";

    public static final int __ENTITY_ID = 8;

    public static final Class<Message> __ENTITY_CLASS = Message.class;

    public static final String __DB_NAME = "Message";

    public static final CursorFactory<Message> __CURSOR_FACTORY = new Factory();

    @Internal
    static final MessageIdGetter __ID_GETTER = new MessageIdGetter();

    public final static Message_ __INSTANCE = new Message_();

    public final static io.objectbox.Property<Message> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<Message> content =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "content");

    public final static io.objectbox.Property<Message> isUser =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, boolean.class, "isUser");

    public final static io.objectbox.Property<Message> timestamp =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, long.class, "timestamp");

    public final static io.objectbox.Property<Message> source =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "source");

    public final static io.objectbox.Property<Message> conversationId =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "conversationId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<Message>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        content,
        isUser,
        timestamp,
        source,
        conversationId
    };

    public final static io.objectbox.Property<Message> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<Message> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<Message>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<Message> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<Message> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<Message> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class MessageIdGetter implements IdGetter<Message> {
        @Override
        public long getId(Message object) {
            return object.id;
        }
    }

    /** To-one relation "conversation" to target entity "Conversation". */
    public static final RelationInfo<Message, Conversation> conversation =
            new RelationInfo<>(Message_.__INSTANCE, Conversation_.__INSTANCE, conversationId, new ToOneGetter<Message, Conversation>() {
                @Override
                public ToOne<Conversation> getToOne(Message entity) {
                    return entity.conversation;
                }
            });

}
