// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "Message".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class MessageCursor extends Cursor<Message> {
    @Internal
    static final class Factory implements CursorFactory<Message> {
        @Override
        public Cursor<Message> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new MessageCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final Message_.MessageIdGetter ID_GETTER = Message_.__ID_GETTER;


    private final static int __ID_content = Message_.content.id;
    private final static int __ID_isUser = Message_.isUser.id;
    private final static int __ID_timestamp = Message_.timestamp.id;
    private final static int __ID_source = Message_.source.id;
    private final static int __ID_conversationId = Message_.conversationId.id;

    public MessageCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, Message_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(Message entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(Message entity) {
        ToOne<Conversation> conversation = entity.conversation;
        if(conversation != null && conversation.internalRequiresPutTarget()) {
            Cursor<Conversation> targetCursor = getRelationTargetCursor(Conversation.class);
            try {
                conversation.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String content = entity.content;
        int __id1 = content != null ? __ID_content : 0;
        String source = entity.source;
        int __id4 = source != null ? __ID_source : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, content, __id4, source,
                0, null, 0, null,
                __ID_timestamp, entity.timestamp, __ID_conversationId, entity.conversation.getTargetId(),
                __ID_isUser, entity.isUser ? 1 : 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        return __assignedId;
    }

}
