// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.SourceFileCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;
import io.objectbox.internal.ToManyGetter;
import io.objectbox.internal.ToOneGetter;
import io.objectbox.relation.RelationInfo;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "SourceFile". Can be used for QueryBuilder and for referencing DB names.
 */
public final class SourceFile_ implements EntityInfo<SourceFile> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "SourceFile";

    public static final int __ENTITY_ID = 9;

    public static final Class<SourceFile> __ENTITY_CLASS = SourceFile.class;

    public static final String __DB_NAME = "SourceFile";

    public static final CursorFactory<SourceFile> __CURSOR_FACTORY = new Factory();

    @Internal
    static final SourceFileIdGetter __ID_GETTER = new SourceFileIdGetter();

    public final static SourceFile_ __INSTANCE = new SourceFile_();

    public final static io.objectbox.Property<SourceFile> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<SourceFile> filePath =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "filePath");

    public final static io.objectbox.Property<SourceFile> fileName =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "fileName");

    public final static io.objectbox.Property<SourceFile> userAlias =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "userAlias");

    public final static io.objectbox.Property<SourceFile> tags =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, String.class, "tags");

    public final static io.objectbox.Property<SourceFile> mimeType =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "mimeType");

    public final static io.objectbox.Property<SourceFile> fileSizeBytes =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, long.class, "fileSizeBytes");

    public final static io.objectbox.Property<SourceFile> fileHash =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, String.class, "fileHash");

    public final static io.objectbox.Property<SourceFile> isIndexed =
        new io.objectbox.Property<>(__INSTANCE, 8, 9, boolean.class, "isIndexed");

    public final static io.objectbox.Property<SourceFile> createdAt =
        new io.objectbox.Property<>(__INSTANCE, 9, 10, long.class, "createdAt");

    public final static io.objectbox.Property<SourceFile> lastModifiedAt =
        new io.objectbox.Property<>(__INSTANCE, 10, 11, long.class, "lastModifiedAt");

    public final static io.objectbox.Property<SourceFile> lastAccessedAt =
        new io.objectbox.Property<>(__INSTANCE, 11, 12, long.class, "lastAccessedAt");

    public final static io.objectbox.Property<SourceFile> folderId =
        new io.objectbox.Property<>(__INSTANCE, 12, 13, long.class, "folderId", true);

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<SourceFile>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        filePath,
        fileName,
        userAlias,
        tags,
        mimeType,
        fileSizeBytes,
        fileHash,
        isIndexed,
        createdAt,
        lastModifiedAt,
        lastAccessedAt,
        folderId
    };

    public final static io.objectbox.Property<SourceFile> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<SourceFile> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<SourceFile>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<SourceFile> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<SourceFile> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<SourceFile> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class SourceFileIdGetter implements IdGetter<SourceFile> {
        @Override
        public long getId(SourceFile object) {
            return object.id;
        }
    }

    /** To-one relation "folder" to target entity "Folder". */
    public static final RelationInfo<SourceFile, Folder> folder =
            new RelationInfo<>(SourceFile_.__INSTANCE, Folder_.__INSTANCE, folderId, new ToOneGetter<SourceFile, Folder>() {
                @Override
                public ToOne<Folder> getToOne(SourceFile entity) {
                    return entity.folder;
                }
            });

    /** To-many relation "chunks" to target entity "DocumentChunk". */
    public static final RelationInfo<SourceFile, DocumentChunk> chunks = new RelationInfo<>(SourceFile_.__INSTANCE, DocumentChunk_.__INSTANCE,
            new ToManyGetter<SourceFile, DocumentChunk>() {
                @Override
                public List<DocumentChunk> getToMany(SourceFile entity) {
                    return entity.chunks;
                }
            },
            DocumentChunk_.sourceFileId,
            new ToOneGetter<DocumentChunk, SourceFile>() {
                @Override
                public ToOne<SourceFile> getToOne(DocumentChunk entity) {
                    return entity.sourceFile;
                }
            });

    /** To-many relation "conversations" to target entity "Conversation". */
    public static final RelationInfo<SourceFile, Conversation> conversations = new RelationInfo<>(SourceFile_.__INSTANCE, Conversation_.__INSTANCE,
            new ToManyGetter<SourceFile, Conversation>() {
                @Override
                public List<Conversation> getToMany(SourceFile entity) {
                    return entity.conversations;
                }
            },
            new ToManyGetter<Conversation, SourceFile>() {
                @Override
                public List<SourceFile> getToMany(Conversation entity) {
                    return entity.referencedFiles;
                }
            }, 1);

}
