// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;
import java.util.List;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "SourceFile".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class SourceFileCursor extends Cursor<SourceFile> {
    @Internal
    static final class Factory implements CursorFactory<SourceFile> {
        @Override
        public Cursor<SourceFile> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new SourceFileCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final SourceFile_.SourceFileIdGetter ID_GETTER = SourceFile_.__ID_GETTER;


    private final static int __ID_filePath = SourceFile_.filePath.id;
    private final static int __ID_fileName = SourceFile_.fileName.id;
    private final static int __ID_userAlias = SourceFile_.userAlias.id;
    private final static int __ID_tags = SourceFile_.tags.id;
    private final static int __ID_mimeType = SourceFile_.mimeType.id;
    private final static int __ID_fileSizeBytes = SourceFile_.fileSizeBytes.id;
    private final static int __ID_fileHash = SourceFile_.fileHash.id;
    private final static int __ID_isIndexed = SourceFile_.isIndexed.id;
    private final static int __ID_createdAt = SourceFile_.createdAt.id;
    private final static int __ID_lastModifiedAt = SourceFile_.lastModifiedAt.id;
    private final static int __ID_lastAccessedAt = SourceFile_.lastAccessedAt.id;
    private final static int __ID_folderId = SourceFile_.folderId.id;

    public SourceFileCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, SourceFile_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(SourceFile entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(SourceFile entity) {
        ToOne<Folder> folder = entity.folder;
        if(folder != null && folder.internalRequiresPutTarget()) {
            Cursor<Folder> targetCursor = getRelationTargetCursor(Folder.class);
            try {
                folder.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String filePath = entity.filePath;
        int __id1 = filePath != null ? __ID_filePath : 0;
        String fileName = entity.fileName;
        int __id2 = fileName != null ? __ID_fileName : 0;
        String userAlias = entity.userAlias;
        int __id3 = userAlias != null ? __ID_userAlias : 0;
        String tags = entity.tags;
        int __id4 = tags != null ? __ID_tags : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, filePath, __id2, fileName,
                __id3, userAlias, __id4, tags);

        String mimeType = entity.mimeType;
        int __id5 = mimeType != null ? __ID_mimeType : 0;
        String fileHash = entity.fileHash;
        int __id7 = fileHash != null ? __ID_fileHash : 0;

        collect313311(cursor, 0, 0,
                __id5, mimeType, __id7, fileHash,
                0, null, 0, null,
                __ID_fileSizeBytes, entity.fileSizeBytes, __ID_createdAt, entity.createdAt,
                __ID_lastModifiedAt, entity.lastModifiedAt, __ID_isIndexed, entity.isIndexed ? 1 : 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                0, null, 0, null,
                0, null, 0, null,
                __ID_lastAccessedAt, entity.lastAccessedAt, __ID_folderId, entity.folder.getTargetId(),
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        entity.__boxStore = boxStoreForEntities;
        checkApplyToManyToDb(entity.chunks, DocumentChunk.class);
        checkApplyToManyToDb(entity.conversations, Conversation.class);
        return __assignedId;
    }

}
