// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "TaskMemory".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class TaskMemoryCursor extends Cursor<TaskMemory> {
    @Internal
    static final class Factory implements CursorFactory<TaskMemory> {
        @Override
        public Cursor<TaskMemory> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new TaskMemoryCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final TaskMemory_.TaskMemoryIdGetter ID_GETTER = TaskMemory_.__ID_GETTER;


    private final static int __ID_taskDescription = TaskMemory_.taskDescription.id;
    private final static int __ID_approach = TaskMemory_.approach.id;
    private final static int __ID_fileIdsUsed = TaskMemory_.fileIdsUsed.id;
    private final static int __ID_embeddingsDiscarded = TaskMemory_.embeddingsDiscarded.id;
    private final static int __ID_completedAt = TaskMemory_.completedAt.id;

    public TaskMemoryCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, TaskMemory_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(TaskMemory entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(TaskMemory entity) {
        String taskDescription = entity.taskDescription;
        int __id1 = taskDescription != null ? __ID_taskDescription : 0;
        String approach = entity.approach;
        int __id2 = approach != null ? __ID_approach : 0;
        String fileIdsUsed = entity.fileIdsUsed;
        int __id3 = fileIdsUsed != null ? __ID_fileIdsUsed : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, taskDescription, __id2, approach,
                __id3, fileIdsUsed, 0, null,
                __ID_completedAt, entity.completedAt, __ID_embeddingsDiscarded, entity.embeddingsDiscarded ? 1 : 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
