// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.TaskMemoryCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "TaskMemory". Can be used for QueryBuilder and for referencing DB names.
 */
public final class TaskMemory_ implements EntityInfo<TaskMemory> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "TaskMemory";

    public static final int __ENTITY_ID = 10;

    public static final Class<TaskMemory> __ENTITY_CLASS = TaskMemory.class;

    public static final String __DB_NAME = "TaskMemory";

    public static final CursorFactory<TaskMemory> __CURSOR_FACTORY = new Factory();

    @Internal
    static final TaskMemoryIdGetter __ID_GETTER = new TaskMemoryIdGetter();

    public final static TaskMemory_ __INSTANCE = new TaskMemory_();

    public final static io.objectbox.Property<TaskMemory> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<TaskMemory> taskDescription =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "taskDescription");

    public final static io.objectbox.Property<TaskMemory> approach =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "approach");

    public final static io.objectbox.Property<TaskMemory> fileIdsUsed =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "fileIdsUsed");

    public final static io.objectbox.Property<TaskMemory> embeddingsDiscarded =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, boolean.class, "embeddingsDiscarded");

    public final static io.objectbox.Property<TaskMemory> completedAt =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, long.class, "completedAt");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<TaskMemory>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        taskDescription,
        approach,
        fileIdsUsed,
        embeddingsDiscarded,
        completedAt
    };

    public final static io.objectbox.Property<TaskMemory> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<TaskMemory> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<TaskMemory>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<TaskMemory> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<TaskMemory> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<TaskMemory> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class TaskMemoryIdGetter implements IdGetter<TaskMemory> {
        @Override
        public long getId(TaskMemory object) {
            return object.id;
        }
    }

}
