// Generated by objectbox/regenerate.sh — do not edit.
package com.android.server.jarvis.model;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "UserContext".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class UserContextCursor extends Cursor<UserContext> {
    @Internal
    static final class Factory implements CursorFactory<UserContext> {
        @Override
        public Cursor<UserContext> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new UserContextCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final UserContext_.UserContextIdGetter ID_GETTER = UserContext_.__ID_GETTER;


    private final static int __ID_preferredName = UserContext_.preferredName.id;
    private final static int __ID_interests = UserContext_.interests.id;
    private final static int __ID_frequentFolders = UserContext_.frequentFolders.id;
    private final static int __ID_lastActiveAt = UserContext_.lastActiveAt.id;
    private final static int __ID_deviceLocale = UserContext_.deviceLocale.id;
    private final static int __ID_facts = UserContext_.facts.id;
    private final static int __ID_consolidatedAt = UserContext_.consolidatedAt.id;

    public UserContextCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, UserContext_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(UserContext entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @SuppressWarnings({"rawtypes", "unchecked"}) 
    @Override
    public long put(UserContext entity) {
        String preferredName = entity.preferredName;
        int __id1 = preferredName != null ? __ID_preferredName : 0;
        String interests = entity.interests;
        int __id2 = interests != null ? __ID_interests : 0;
        String frequentFolders = entity.frequentFolders;
        int __id3 = frequentFolders != null ? __ID_frequentFolders : 0;
        String deviceLocale = entity.deviceLocale;
        int __id5 = deviceLocale != null ? __ID_deviceLocale : 0;

        collect400000(cursor, 0, PUT_FLAG_FIRST,
                __id1, preferredName, __id2, interests,
                __id3, frequentFolders, __id5, deviceLocale);

        String facts = entity.facts;
        int __id6 = facts != null ? __ID_facts : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_COMPLETE,
                __id6, facts, 0, null,
                0, null, 0, null,
                __ID_lastActiveAt, entity.lastActiveAt, __ID_consolidatedAt, entity.consolidatedAt,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        return __assignedId;
    }

}
