// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.model;

import com.android.server.jarvis.model.UserContextCursor.Factory;
import io.objectbox.EntityInfo;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "UserContext". Can be used for QueryBuilder and for referencing DB names.
 */
public final class UserContext_ implements EntityInfo<UserContext> {

    // Leading underscores for static constants to avoid naming conflicts with property names

    public static final String __ENTITY_NAME = "UserContext";

    public static final int __ENTITY_ID = 12;

    public static final Class<UserContext> __ENTITY_CLASS = UserContext.class;

    public static final String __DB_NAME = "UserContext";

    public static final CursorFactory<UserContext> __CURSOR_FACTORY = new Factory();

    @Internal
    static final UserContextIdGetter __ID_GETTER = new UserContextIdGetter();

    public final static UserContext_ __INSTANCE = new UserContext_();

    public final static io.objectbox.Property<UserContext> id =
        new io.objectbox.Property<>(__INSTANCE, 0, 1, long.class, "id", true, "id");

    public final static io.objectbox.Property<UserContext> preferredName =
        new io.objectbox.Property<>(__INSTANCE, 1, 2, String.class, "preferredName");

    public final static io.objectbox.Property<UserContext> interests =
        new io.objectbox.Property<>(__INSTANCE, 2, 3, String.class, "interests");

    public final static io.objectbox.Property<UserContext> frequentFolders =
        new io.objectbox.Property<>(__INSTANCE, 3, 4, String.class, "frequentFolders");

    public final static io.objectbox.Property<UserContext> lastActiveAt =
        new io.objectbox.Property<>(__INSTANCE, 4, 5, long.class, "lastActiveAt");

    public final static io.objectbox.Property<UserContext> deviceLocale =
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "deviceLocale");

    public final static io.objectbox.Property<UserContext> facts =
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "facts");

    public final static io.objectbox.Property<UserContext> consolidatedAt =
        new io.objectbox.Property<>(__INSTANCE, 7, 8, long.class, "consolidatedAt");

    @SuppressWarnings("unchecked")
    public final static io.objectbox.Property<UserContext>[] __ALL_PROPERTIES = new io.objectbox.Property[]{
        id,
        preferredName,
        interests,
        frequentFolders,
        lastActiveAt,
        deviceLocale,
        facts,
        consolidatedAt
    };

    public final static io.objectbox.Property<UserContext> __ID_PROPERTY = id;

    @Override
    public String getEntityName() {
        return __ENTITY_NAME;
    }

    @Override
    public int getEntityId() {
        return __ENTITY_ID;
    }

    @Override
    public Class<UserContext> getEntityClass() {
        return __ENTITY_CLASS;
    }

    @Override
    public String getDbName() {
        return __DB_NAME;
    }

    @Override
    public io.objectbox.Property<UserContext>[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public io.objectbox.Property<UserContext> getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public IdGetter<UserContext> getIdGetter() {
        return __ID_GETTER;
    }

    @Override
    public CursorFactory<UserContext> getCursorFactory() {
        return __CURSOR_FACTORY;
    }

    @Internal
    static final class UserContextIdGetter implements IdGetter<UserContext> {
        @Override
        public long getId(UserContext object) {
            return object.id;
        }
    }

}
