// Generated by objectbox/regenerate.sh — do not edit.

package com.android.server.jarvis.core;

import com.android.server.jarvis.model.AccessLog;
import com.android.server.jarvis.model.AccessLogCursor;
import com.android.server.jarvis.model.AccessLog_;
import com.android.server.jarvis.model.AgentSession;
import com.android.server.jarvis.model.AgentSessionCursor;
import com.android.server.jarvis.model.AgentSession_;
import com.android.server.jarvis.model.AgentTurn;
import com.android.server.jarvis.model.AgentTurnCursor;
import com.android.server.jarvis.model.AgentTurn_;
import com.android.server.jarvis.model.Conversation;
import com.android.server.jarvis.model.ConversationCursor;
import com.android.server.jarvis.model.Conversation_;
import com.android.server.jarvis.model.DocumentChunk;
import com.android.server.jarvis.model.DocumentChunkCursor;
import com.android.server.jarvis.model.DocumentChunk_;
import com.android.server.jarvis.model.Folder;
import com.android.server.jarvis.model.FolderCursor;
import com.android.server.jarvis.model.Folder_;
import com.android.server.jarvis.model.Message;
import com.android.server.jarvis.model.MessageCursor;
import com.android.server.jarvis.model.Message_;
import com.android.server.jarvis.model.SourceFile;
import com.android.server.jarvis.model.SourceFileCursor;
import com.android.server.jarvis.model.SourceFile_;
import com.android.server.jarvis.model.TaskMemory;
import com.android.server.jarvis.model.TaskMemoryCursor;
import com.android.server.jarvis.model.TaskMemory_;
import com.android.server.jarvis.model.UserContext;
import com.android.server.jarvis.model.UserContextCursor;
import com.android.server.jarvis.model.UserContext_;
import com.android.server.jarvis.tools.AppRecord;
import com.android.server.jarvis.tools.AppRecordCursor;
import com.android.server.jarvis.tools.AppRecord_;
import com.android.server.jarvis.tools.ToolRecord;
import com.android.server.jarvis.tools.ToolRecordCursor;
import com.android.server.jarvis.tools.ToolRecord_;
import io.objectbox.BoxStore;
import io.objectbox.BoxStoreBuilder;
import io.objectbox.ModelBuilder;
import io.objectbox.ModelBuilder.EntityBuilder;
import io.objectbox.model.PropertyFlags;
import io.objectbox.model.PropertyType;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.
/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 * <p>
 * First steps (Android): get a builder using {@link #builder()}, call {@link BoxStoreBuilder#androidContext(Object)},
 * and {@link BoxStoreBuilder#build()} to get a {@link BoxStore} to work with.
 */
public class MyObjectBox {

    public static BoxStoreBuilder builder() {
        BoxStoreBuilder builder = new BoxStoreBuilder(getModel());
        builder.entity(AccessLog_.__INSTANCE);
        builder.entity(AgentSession_.__INSTANCE);
        builder.entity(AgentTurn_.__INSTANCE);
        builder.entity(AppRecord_.__INSTANCE);
        builder.entity(Conversation_.__INSTANCE);
        builder.entity(DocumentChunk_.__INSTANCE);
        builder.entity(Folder_.__INSTANCE);
        builder.entity(Message_.__INSTANCE);
        builder.entity(SourceFile_.__INSTANCE);
        builder.entity(TaskMemory_.__INSTANCE);
        builder.entity(ToolRecord_.__INSTANCE);
        builder.entity(UserContext_.__INSTANCE);
        return builder;
    }

    private static byte[] getModel() {
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.lastEntityId(12, 3333842739942764369L);
        modelBuilder.lastIndexId(6, 3379031151269064229L);
        modelBuilder.lastRelationId(1, 3455510513232033727L);

        buildEntityAccessLog(modelBuilder);
        buildEntityAgentSession(modelBuilder);
        buildEntityAgentTurn(modelBuilder);
        buildEntityAppRecord(modelBuilder);
        buildEntityConversation(modelBuilder);
        buildEntityDocumentChunk(modelBuilder);
        buildEntityFolder(modelBuilder);
        buildEntityMessage(modelBuilder);
        buildEntitySourceFile(modelBuilder);
        buildEntityTaskMemory(modelBuilder);
        buildEntityToolRecord(modelBuilder);
        buildEntityUserContext(modelBuilder);

        return modelBuilder.build();
    }

    private static void buildEntityAccessLog(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("AccessLog");
        entityBuilder.id(1, 5865185351678958405L).lastPropertyId(5, 6444628611872497061L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 8805437090273078666L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("fileId", PropertyType.Long).id(2, 4361353715204459624L);
        entityBuilder.property("conversationId", PropertyType.Long).id(3, 4015084259504197812L);
        entityBuilder.property("accessedAt", PropertyType.Long).id(4, 8949923929063440688L);
        entityBuilder.property("wasHelpful", PropertyType.Bool).id(5, 6444628611872497061L);


        entityBuilder.entityDone();
    }

    private static void buildEntityAgentSession(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("AgentSession");
        entityBuilder.id(2, 8993120973033714162L).lastPropertyId(13, 3655138000573453920L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 9066011117230712215L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("sessionId", PropertyType.String).id(2, 4781500811389717661L);
        entityBuilder.property("originalQuery", PropertyType.String).id(3, 1472336787599788482L);
        entityBuilder.property("currentPlan", PropertyType.String).id(4, 974697612039431209L);
        entityBuilder.property("lastToolResult", PropertyType.String).id(5, 7292233678790929992L);
        entityBuilder.property("accumulatedContext", PropertyType.String).id(6, 2736348219590538756L);
        entityBuilder.property("turnCount", PropertyType.Int).id(7, 2002142223898404321L);
        entityBuilder.property("maxTurns", PropertyType.Int).id(8, 1563643957480379853L);
        entityBuilder.property("status", PropertyType.String).id(9, 4622658663220864407L);
        entityBuilder.property("finalAnswer", PropertyType.String).id(10, 2994745555149246273L);
        entityBuilder.property("createdAt", PropertyType.Long).id(11, 7091951776671932025L);
        entityBuilder.property("lastUpdatedAt", PropertyType.Long).id(12, 3091877501750297484L);
        entityBuilder.property("consolidated", PropertyType.Bool).id(13, 3655138000573453920L);


        entityBuilder.entityDone();
    }

    private static void buildEntityAgentTurn(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("AgentTurn");
        entityBuilder.id(3, 8344271588581838447L).lastPropertyId(7, 3412710813658673535L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 1642468120786338368L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("role", PropertyType.String).id(2, 4704496076042695513L);
        entityBuilder.property("content", PropertyType.String).id(3, 7030930680933494753L);
        entityBuilder.property("toolName", PropertyType.String).id(4, 4691511503591736343L);
        entityBuilder.property("toolArgs", PropertyType.String).id(5, 2533921121272794736L);
        entityBuilder.property("timestamp", PropertyType.Long).id(6, 6103233569354302238L);
        entityBuilder.property("sessionId", "AgentSession", "session", PropertyType.Relation).id(7, 3412710813658673535L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(1, 1180267484368479608L);


        entityBuilder.entityDone();
    }

    private static void buildEntityAppRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("AppRecord");
        entityBuilder.id(4, 104837957485342565L).lastPropertyId(6, 2563489744931152613L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 298893425102039614L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("packageName", PropertyType.String).id(2, 6131526216535556763L);
        entityBuilder.property("appLabel", PropertyType.String).id(3, 3015904084672860179L);
        entityBuilder.property("sourceType", PropertyType.String).id(4, 2078547040453812772L);
        entityBuilder.property("lastScanTime", PropertyType.Long).id(5, 7966209900454578334L);
        entityBuilder.property("isActive", PropertyType.Bool).id(6, 2563489744931152613L);


        entityBuilder.entityDone();
    }

    private static void buildEntityConversation(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Conversation");
        entityBuilder.id(5, 2819767465062455882L).lastPropertyId(6, 3482726999944577583L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 196234483410251333L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("title", PropertyType.String).id(2, 4095354392991821465L);
        entityBuilder.property("createdAt", PropertyType.Long).id(3, 7724910737756867443L);
        entityBuilder.property("lastMessageAt", PropertyType.Long).id(4, 5839641827895665569L);
        entityBuilder.property("lastMessagePreview", PropertyType.String).id(5, 6947091190784573782L);
        entityBuilder.property("mode", PropertyType.String).id(6, 3482726999944577583L);

        entityBuilder.relation("referencedFiles", 1, 3455510513232033727L, 9, 8712196067765286206L);

        entityBuilder.entityDone();
    }

    private static void buildEntityDocumentChunk(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("DocumentChunk");
        entityBuilder.id(6, 6878213906180263136L).lastPropertyId(8, 3355500354216602402L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 4731657768460388465L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("cactusIndexId", PropertyType.Int).id(2, 6139962230787098058L);
        entityBuilder.property("chunkIndex", PropertyType.Int).id(3, 5513938961769879923L);
        entityBuilder.property("summary", PropertyType.String).id(4, 7661666537744062772L);
        entityBuilder.property("tokenCount", PropertyType.Int).id(5, 6661415160980489264L);
        entityBuilder.property("embeddedAt", PropertyType.Long).id(6, 574717536663365352L);
        entityBuilder.property("embeddingRetained", PropertyType.Bool).id(7, 5122033646772071338L);
        entityBuilder.property("sourceFileId", "SourceFile", "sourceFile", PropertyType.Relation).id(8, 3355500354216602402L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(2, 5961109128535499620L);


        entityBuilder.entityDone();
    }

    private static void buildEntityFolder(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Folder");
        entityBuilder.id(7, 8884378356230875581L).lastPropertyId(8, 9096815286276287908L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 8588238720434459586L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("folderPath", PropertyType.String).id(2, 956083410901755080L);
        entityBuilder.property("displayName", PropertyType.String).id(3, 4936382503614434706L);
        entityBuilder.property("tags", PropertyType.String).id(4, 4722669162723652282L);
        entityBuilder.property("summary", PropertyType.String).id(5, 879163776849233740L);
        entityBuilder.property("fileCount", PropertyType.Int).id(6, 2029611348229269562L);
        entityBuilder.property("lastUpdatedAt", PropertyType.Long).id(7, 5701573469841092888L);
        entityBuilder.property("parentFolderId", "Folder", "parentFolder", PropertyType.Relation).id(8, 9096815286276287908L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(3, 8869471228172267601L);


        entityBuilder.entityDone();
    }

    private static void buildEntityMessage(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("Message");
        entityBuilder.id(8, 5328290195839763856L).lastPropertyId(6, 3285158787498915498L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 4845771595044232933L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("content", PropertyType.String).id(2, 4753852696201058306L);
        entityBuilder.property("isUser", PropertyType.Bool).id(3, 6712752765425535274L);
        entityBuilder.property("timestamp", PropertyType.Long).id(4, 792122502436522332L);
        entityBuilder.property("source", PropertyType.String).id(5, 1614215718003036058L);
        entityBuilder.property("conversationId", "Conversation", "conversation", PropertyType.Relation).id(6, 3285158787498915498L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(4, 3733890296287014422L);


        entityBuilder.entityDone();
    }

    private static void buildEntitySourceFile(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("SourceFile");
        entityBuilder.id(9, 8712196067765286206L).lastPropertyId(13, 9055962025321565488L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 5042665544981329124L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("filePath", PropertyType.String).id(2, 732866389784633914L);
        entityBuilder.property("fileName", PropertyType.String).id(3, 4905331227139571546L);
        entityBuilder.property("userAlias", PropertyType.String).id(4, 7367546884604866602L);
        entityBuilder.property("tags", PropertyType.String).id(5, 5440067477077841394L);
        entityBuilder.property("mimeType", PropertyType.String).id(6, 5212369903827824089L);
        entityBuilder.property("fileSizeBytes", PropertyType.Long).id(7, 5726620894575425541L);
        entityBuilder.property("fileHash", PropertyType.String).id(8, 616249601107533534L);
        entityBuilder.property("isIndexed", PropertyType.Bool).id(9, 8447013533571552152L);
        entityBuilder.property("createdAt", PropertyType.Long).id(10, 5500376151147682257L);
        entityBuilder.property("lastModifiedAt", PropertyType.Long).id(11, 2616338058356603009L);
        entityBuilder.property("lastAccessedAt", PropertyType.Long).id(12, 6582351692640160458L);
        entityBuilder.property("folderId", "Folder", "folder", PropertyType.Relation).id(13, 9055962025321565488L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(5, 3169313819964008698L);


        entityBuilder.entityDone();
    }

    private static void buildEntityTaskMemory(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("TaskMemory");
        entityBuilder.id(10, 2163637672977749695L).lastPropertyId(6, 8856747766195001777L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 698516752549413803L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("taskDescription", PropertyType.String).id(2, 2684801778216575477L);
        entityBuilder.property("approach", PropertyType.String).id(3, 6145159778552697251L);
        entityBuilder.property("fileIdsUsed", PropertyType.String).id(4, 7133092720675676720L);
        entityBuilder.property("embeddingsDiscarded", PropertyType.Bool).id(5, 7813117688186960884L);
        entityBuilder.property("completedAt", PropertyType.Long).id(6, 8856747766195001777L);


        entityBuilder.entityDone();
    }

    private static void buildEntityToolRecord(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("ToolRecord");
        entityBuilder.id(11, 8287128223032117862L).lastPropertyId(9, 8084968176320758193L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 4986841424643759923L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("toolName", PropertyType.String).id(2, 2359149922621922661L);
        entityBuilder.property("description", PropertyType.String).id(3, 8099268941384063380L);
        entityBuilder.property("paramsJson", PropertyType.String).id(4, 2739069215333386637L);
        entityBuilder.property("rawDefinition", PropertyType.String).id(5, 2438754035942828951L);
        entityBuilder.property("receiverClass", PropertyType.String).id(6, 6051490870532594631L);
        entityBuilder.property("cactusIndexId", PropertyType.Int).id(7, 4501491613299824035L);
        entityBuilder.property("requiresConfirmation", PropertyType.Bool).id(8, 3457298276641835258L);
        entityBuilder.property("appId", "AppRecord", "app", PropertyType.Relation).id(9, 8084968176320758193L)
                .flags(PropertyFlags.VIRTUAL | PropertyFlags.INDEXED | PropertyFlags.INDEX_PARTIAL_SKIP_ZERO).indexId(6, 3379031151269064229L);


        entityBuilder.entityDone();
    }

    private static void buildEntityUserContext(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("UserContext");
        entityBuilder.id(12, 3333842739942764369L).lastPropertyId(8, 6215560427882673488L);
        entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR);

        entityBuilder.property("id", PropertyType.Long).id(1, 5348133900628657467L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("preferredName", PropertyType.String).id(2, 1485255517776348362L);
        entityBuilder.property("interests", PropertyType.String).id(3, 2708577421185822933L);
        entityBuilder.property("frequentFolders", PropertyType.String).id(4, 3319309978130566065L);
        entityBuilder.property("lastActiveAt", PropertyType.Long).id(5, 6962625921946928238L);
        entityBuilder.property("deviceLocale", PropertyType.String).id(6, 4775636622302912304L);
        entityBuilder.property("facts", PropertyType.String).id(7, 3673361999979423543L);
        entityBuilder.property("consolidatedAt", PropertyType.Long).id(8, 6215560427882673488L);


        entityBuilder.entityDone();
    }


}
